insert into shops values (1, 'Rewe', 'Karl Lag Street, 45', 'SUPERMARKET');
insert into shops values (2, 'Lidl', 'Zentralle Strasse, 1 A', 'SUPERMARKET');
insert into shops values (3, 'Edeka', 'Metzger Strasse, 13', 'SUPERMARKET');
insert into shops values (4, 'У Тамары', 'Сами без понятия', 'KIOSK');
insert into shops values (5, 'Посад', 'метро Холодная Гора', 'SHOP');
insert into shops values (6, 'На углу', 'С торца дома дочери маминой подруги', 'KIOSK');
insert into shops values (7, 'Кулиничи', 'Возле любого метро', 'SHOP');

insert into products values (1, 'Juice Jaffa', 'LIQUID', 50.0, 'juice', 13.5);
insert into products values (2, 'Tomato', 'VEGETABLE', 51.3, 'juice', 54.5);
insert into products values (3, 'Apple', 'FRUIT', 52.5, 'juice', 15.5);
insert into products values (4, 'Beef', 'MEET', 100.1, 'juice', 10.0);
insert into products values (5, 'Ferrero Rocher', 'SWEET', 239.5, 'juice', 500.5);
insert into products values (6, 'Oreo', 'SWEET', 23.7, 'juice', 17.2);
insert into products values (7, 'Barni', 'SWEET', 20.9, 'juice', 10.3);
insert into products values (8, 'Morshinska', 'LIQUID', 30.1, 'juice', 33.4);
insert into products values (9, 'Lays', 'SNACK', 34.5, 'juice', 33.9);
insert into products values (10, 'Pepper', 'VEGETABLE', 30.4, 'juice', 111.6);
insert into products values (11, 'Nutella', 'OTHER', 90.0, 'juice', 144.5);

insert into shop_product values (1, 1);
insert into shop_product values (1, 2);
insert into shop_product values (2, 3);
insert into shop_product values (3, 4);
insert into shop_product values (4, 5);
insert into shop_product values (5, 6);
insert into shop_product values (5, 7);
insert into shop_product values (5, 8);
insert into shop_product values (6, 9);
insert into shop_product values (6, 10);
insert into shop_product values (6, 11);
insert into shop_product values (7, 1);
insert into shop_product values (7, 2);
insert into shop_product values (7, 3);
insert into shop_product values (2, 4);
insert into shop_product values (1, 5);
insert into shop_product values (3, 6);
insert into shop_product values (1, 8);
insert into shop_product values (3, 9);
insert into shop_product values (3, 10);
insert into shop_product values (4, 11);
insert into shop_product values (4, 10);
insert into shop_product values (6, 2);
insert into shop_product values (3, 3);
insert into shop_product values (7, 4);
insert into shop_product values (6, 5);
insert into shop_product values (7, 6);
insert into shop_product values (7, 7);
